name: raspberry_system_monitor
description: Raspberry System Monitor
version: 1.0.2+38

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.22.2
  http: ^0.12.0+2
  built_value: ^6.7.1
  built_collection: any
  shared_preferences: ^0.5.3+4
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.9
  built_value_generator: ^6.7.1
  flutter_launcher_icons: ^0.7.3
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
