name: raspberry_system_monitor
description: Raspberry System Monitor
version: 1.0.2+47

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  rxdart: ^0.24.0
  http: ^0.12.0+4
  built_value: ^7.1.0
  built_collection: ^4.3.2
  shared_preferences: ^0.5.7
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
