name: raspberry_system_monitor
description: Raspberry System Monitor
version: 1.0.3+57

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.5
  http: ^0.13.5
  built_value: ^8.4.2
  built_collection: ^5.1.1
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  built_value_generator: ^8.4.2
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/pi4_board_new.png