name: raspberrymonitor # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.2+teamcity' # just for humans, typically '1.2+git' or '1.3.2'
summary: raspberry system monitor # 79 char long summary
description: |
  raspberry system monitor build with flutter

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: assets/icon.png

parts:
  raspberrymonitor:
    stage-packages:
      - libgl1
      - libgtk-3-dev
      - libglfw3
      - libgl1-mesa-dri
      - libqt5core5a
      - libqt5network5
      - libxcomposite1
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libatk1.0-0
      - libgtk2.0-0
    plugin: dump
    source: build/linux/1.zip

apps:
  raspberrymonitor:
    command: desktop-launch $SNAP/release/raspberry_system_monitor
    plugs: [opengl, x11, wayland, network, network-bind, desktop, desktop-legacy]