name: raspberrymonitor # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.2+teamcity' # just for humans, typically '1.2+git' or '1.3.2'
summary: raspberry system monitor # 79 char long summary
description: |
  raspberry system monitor build with flutter

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: assets/icon.png

parts:
  raspberrymonitor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libegl1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libglvnd0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0

apps:
  raspberrymonitor:
    command: raspberrymonitor
    extensions: [flutter-master]
    plugs: [network]