name: raspberrymonitor # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.2+teamcity' # just for humans, typically '1.2+git' or '1.3.2'
summary: raspberry system monitor # 79 char long summary
description: |
  raspberry system monitor build with flutter

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: assets/icon.png

parts:
  raspberrymonitor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

apps:
  raspberrymonitor:
    command: raspberrymonitor
    extensions: [flutter-master]
    plugs: [network]